-- PAK DEBATE FORUM — Seed Data (dummy content for development)
-- Apply with: wrangler d1 execute DB --local --file=seed.sql

-- Coaches
INSERT INTO coaches (name, title, bio, expertise, active) VALUES
('Zara Ahmed', 'Head Coach & Founder', 'Former national champion debater with 8 years of coaching experience. Oxford Summer Programme alumna. Trained over 400 students across Pakistan.', '["World Schools","British Parliamentary","POI Technique","Adjudication"]', 1),
('Hassan Malik', 'Senior Debate Coach', 'National debate finalist and experienced BP adjudicator. Specialises in training intermediate to advanced debaters for national circuit competitions.', '["British Parliamentary","Research Methods","Argument Construction"]', 1),
('Ayesha Siddiqui', 'Public Speaking Coach', 'TEDx speaker and corporate communications trainer. Brings executive presence coaching to student debaters. 5 years of public speaking instruction.', '["Public Speaking","Presentation Skills","Confidence Building","MUN"]', 1),
('Bilal Chaudhry', 'Junior Programme Lead', 'University debate champion. Specialises in introducing debate to students with no prior experience in a structured, encouraging environment.', '["World Schools","Beginners Curriculum","Youth Development"]', 1),
('Sara Khan', 'Writing & Research Coach', 'Academic writing specialist with background in journalism. Coaches students for essay competitions and research-based debate formats.', '["Academic Writing","Research Skills","Essay Competitions","Lincoln-Douglas"]', 1);

-- Programs
INSERT INTO programs (slug, title, category, level, age_min, age_max, duration, delivery_mode, description, curriculum, schedule, price, active, coach_id) VALUES
('beginner-debate', 'Beginner Debate Training', 'debate', 'beginner', 12, 17, '10 weeks', 'hybrid', 'An entry-level programme designed to introduce competitive debate to students with little or no prior experience. Students will learn argument construction, rebuttal techniques, and the fundamentals of World Schools debate format in a structured and supportive environment.', '["Week 1-2: Introduction to debate formats and rules","Week 3-4: Building arguments and evidence","Week 5-6: Rebuttal and counter-argument techniques","Week 7-8: Points of Information (POIs)","Week 9: Mock tournament preparation","Week 10: Internal tournament and assessment"]', 'Saturdays, 10:00am – 12:00pm', 12000, 1, 4),

('advanced-competitive', 'Advanced Competitive Track', 'debate', 'advanced', 15, 22, '12 weeks', 'in_person', 'An intensive programme for experienced debaters targeting regional, national, and international competition. Covers advanced argumentation, BP format mastery, adjudication skills, and tournament strategy. Includes practice rounds against coaches and external partners.', '["Weeks 1-3: Advanced BP strategy and case construction","Weeks 4-5: Cross-examination and challenge rounds","Weeks 6-7: Adjudication training and ballot analysis","Weeks 8-9: Research methodology and motion analysis","Weeks 10-11: Mock tournament (BP and WS)","Week 12: Performance review and competition roadmap"]', 'Tuesdays & Thursdays, 5:00pm – 7:30pm', 25000, 1, 2),

('public-speaking', 'Confidence & Public Speaking', 'public_speaking', 'all', 13, 25, '8 weeks', 'hybrid', 'A confidence-building programme focused on public speaking, presentation skills, and executive communication. Suitable for students preparing for MUNs, school presentations, and anyone who wants to speak with clarity and authority in public settings.', '["Week 1-2: Foundation — posture, voice, and eye contact","Week 3: Structuring a speech","Week 4: Storytelling and audience engagement","Week 5: Impromptu speaking and Q&A handling","Week 6: Presentation design and visual aids","Week 7: Recorded practice sessions and feedback","Week 8: Final presentations and certification"]', 'Sundays, 11:00am – 1:00pm', 10000, 1, 3),

('intermediate-worlds', 'World Schools Intermediate', 'debate', 'intermediate', 14, 19, '10 weeks', 'in_person', 'A structured programme for students who have completed beginner training or have some debate experience. Focuses on World Schools format with emphasis on style, matter, and manner — the three pillars of WS adjudication.', '["Weeks 1-2: WS format deep dive — roles and responsibilities","Weeks 3-4: Matter: building substantive arguments","Weeks 5-6: Manner: delivery, style, and presence","Weeks 7-8: Method: case strategy and team dynamics","Week 9: Full practice tournaments with adjudication","Week 10: Individual feedback and progression assessment"]', 'Wednesdays & Fridays, 4:00pm – 6:00pm', 18000, 1, 1),

('essay-writing', 'Academic Essay & Writing Programme', 'writing', 'intermediate', 15, 22, '6 weeks', 'online', 'A research and writing programme designed to help students produce high-quality argumentative essays for competitions such as the John Locke Institute and similar academic contests. Covers thesis construction, source evaluation, and persuasive writing.', '["Week 1: Choosing and narrowing your topic","Week 2: Academic research and source evaluation","Week 3: Thesis and argument structure","Week 4: Writing the body — evidence and analysis","Week 5: Introduction, conclusion, and transitions","Week 6: Peer review and final submission polishing"]', 'Mondays, 6:00pm – 8:00pm (Online)', 8000, 1, 5),

('summer-intensive', 'Summer Debate Intensive', 'workshop', 'all', 13, 20, '5 days', 'in_person', 'A five-day residential-style summer camp covering debate, public speaking, and critical thinking. Includes mock tournaments, guest speakers, adjudication workshops, and team-building activities. Limited to 30 participants per cohort.', '["Day 1: Orientation, format overview, team formation","Day 2: Argument and case building workshops","Day 3: Full-day BP tournament (practice)","Day 4: Public speaking masterclass + individual coaching","Day 5: Championship round, awards, and certificates"]', 'July — dates vary per cohort', 35000, 1, 1);

-- Events
INSERT INTO events (slug, title, type, description, venue, city, date_start, date_end, registration_deadline, max_participants, fee, status, program_id) VALUES
('national-schools-2026', 'National Schools Debate Championship 2026', 'tournament', 'Pakistan''s most prestigious inter-school debate competition. Open to schools from all provinces. World Schools format. Three-person teams. Separate categories for junior (Grades 8-10) and senior (Grades 11-12) divisions.', 'Lahore Grammar School Auditorium', 'Lahore', '2026-09-15', '2026-09-17', '2026-08-31', 64, 5000, 'open', NULL),

('bp-open-karachi', 'Karachi Open — British Parliamentary', 'tournament', 'A British Parliamentary open tournament welcoming debaters from universities and schools across Sindh. Individual speakers only — pairs formed at draw. WUDC rules apply. Trophies and cash prizes for top speakers.', 'IBA City Campus', 'Karachi', '2026-10-03', '2026-10-04', '2026-09-20', 80, 3500, 'open', NULL),

('beginner-workshop-aug', 'Introduction to Debate — Free Workshop', 'workshop', 'A free, 3-hour introductory workshop for students who have never debated before. Covers what debate is, how tournaments work, and what the Academy offers. Ideal for students considering joining a programme. Parents welcome.', 'Pak Debate Forum Academy Centre', 'Islamabad', '2026-08-24', NULL, '2026-08-22', 40, 0, 'open', 1),

('summer-camp-aug', 'Summer Debate Intensive — August Cohort', 'camp', 'Our flagship 5-day Summer Intensive Programme for students ages 13-20. Covers debate, public speaking, and critical thinking. Full details on the programme page. Only a few seats remaining for the August cohort.', 'Roots International School', 'Rawalpindi', '2026-08-25', '2026-08-29', '2026-08-18', 30, 35000, 'open', 6),

('adjudication-training', 'Certified Adjudication Training Workshop', 'workshop', 'A full-day workshop for students and adults who wish to become certified debate adjudicators. Covers adjudication philosophy, ballot writing, speaker feedback, and chairing. Participants receive a Pak Debate Forum adjudication certificate upon completion.', 'Virtual (Zoom)', 'Online', '2026-09-06', NULL, '2026-09-03', 25, 2500, 'upcoming', NULL),

('world-schools-prep', 'World Schools Tournament Preparation Camp', 'camp', 'A 3-day preparation camp for teams selected to represent their schools at national or international World Schools tournaments. By invitation only — contact us to check eligibility.', 'Beacon House School System', 'Lahore', '2026-11-07', '2026-11-09', '2026-10-25', 20, 15000, 'upcoming', 4);

-- Resources
INSERT INTO resources (title, category, description, url, file_type, active) VALUES
('World Schools Debate Format Guide', 'formats', 'Complete guide to the World Schools (WSDC) debate format — roles, timing, scoring, and rules.', 'https://example.com/ws-guide.pdf', 'pdf', 1),
('British Parliamentary Format Handbook', 'formats', 'A detailed handbook explaining the British Parliamentary debate format used in university and open competitions.', 'https://example.com/bp-handbook.pdf', 'pdf', 1),
('100 Practice Motions — All Levels', 'motions', 'A curated list of 100 practice motions organised by topic and difficulty. Great for self-study and practice rounds.', 'https://example.com/motions-100.pdf', 'pdf', 1),
('Argument Construction Worksheet', 'guides', 'A structured worksheet template for building PEEL-format arguments with evidence and impact.', 'https://example.com/argument-worksheet.pdf', 'pdf', 1),
('How to Write a Rebuttal — Step by Step', 'guides', 'A beginner-friendly guide breaking down the rebuttal process into clear, repeatable steps.', 'https://example.com/rebuttal-guide.pdf', 'pdf', 1),
('National Schools Championship 2025 — Results & Ballots', 'results', 'Official results, team rankings, and selected speaker ballots from the 2025 National Schools Championship.', 'https://example.com/nsdc-2025-results.pdf', 'pdf', 1),
('POI Technique Masterclass — Video', 'videos', 'A 45-minute video session on Points of Information technique, timing, and strategy from Coach Hassan Malik.', 'https://example.com/poi-masterclass', 'video', 1),
('Introduction to Adjudication — Video Series', 'videos', 'A four-part video series introducing debate adjudication philosophy and practical ballot writing.', 'https://example.com/adjudication-series', 'video', 1);
